#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo"
name = "Forgejo"
description.en = "Lightweight software forge"
description.fr = "Forge logiciel légère"
description.de = "Leichtgewichtige Software-Forge"

version = "15.0.3~ynh1"

maintainers = [ "Emmanuel Averty", "Josué Tille" ]

[upstream]
license = "GPL-3.0-or-later"
website = "https://forgejo.org"
admindoc = "https://forgejo.org/docs/latest/admin/"
userdoc = "https://forgejo.org/docs/latest/user/"
code = "https://codeberg.org/forgejo/forgejo"

[integration]
yunohost = ">= 12.1.40.1"
helpers_version = "2.1"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = true
sso = true

disk = "150M"
ram.build = "50M"
ram.runtime = "2G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/forgejo"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Which group will have access to Forgejo admin page?"
    ask.fr = "Quel groupe aura accès à l'administration de Forgejo ?"
    ask.de = "Welche Gruppe soll Zugriff auf die Forgejo Administrationsseite erhalten?"
    help.en = "Users of this group should have access to Forgejo admin page"
    help.fr = "Les utilisateurs de ce groupe devrait avoir accès à la page d'administration de Forgejo"
    help.de = "Benutzer in dieser Gruppe sollen Zugriff auf die Forgejo Administrationsseite erhalten."
    type = "group"
    default = "admins"

[resources]
    [resources.sources.main]
    amd64.url = "https://codeberg.org/forgejo/forgejo/releases/download/v15.0.3/forgejo-15.0.3-linux-amd64.xz"
    amd64.sha256 = "4afcb279139a554ad6fe910050065ff76adad823051994d200b509bfc3c94d7b"
    arm64.url = "https://codeberg.org/forgejo/forgejo/releases/download/v15.0.3/forgejo-15.0.3-linux-arm64.xz"
    arm64.sha256 = "146b069b4007a0e10257293c697323f761a98e57cdc4602883a38b763bcec11f"
    armhf.url = "https://codeberg.org/forgejo/forgejo/releases/download/v15.0.3/forgejo-15.0.3-linux-arm-6.xz"
    armhf.sha256 = "bc54f5a7feacf6f89d78a1ff63daa67305fe95320d3df1b92ae2797d09478816"
    format = "whatever"
    extract = false
    rename = "forgejo.xz"

    autoupdate.asset.amd64 = "^forgejo-.*-linux-amd64.xz$"
    autoupdate.asset.arm64 = "^forgejo-.*-linux-arm64.xz$"
    autoupdate.asset.armhf = "^forgejo-.*-linux-arm-6.xz$"
    autoupdate.strategy = "latest_forgejo_release"

    [resources.system_user]
    allow_ssh = true
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    admin.show_tile = false
    admin.auth_header = false
    admin.protected = true

    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    container_registry.show_tile = false
    container_registry.auth_header = false
    container_registry.label = "Container registry"
    container_registry.url = "__DOMAIN__/v2"
    container_registry.allowed = "visitors"

    [resources.ports]
    main.default = 6000

    [resources.apt]
    packages = "postgresql, git, git-lfs"

    [resources.database]
    type = "postgresql"
