#!/bin/bash

YNH_HELPERS_VERSION=2.1

###
# This hook is only used because yunohost doesn't trigger any hook when adding a user to a group (e.g. admin)
# After adding a user to a group, one should update a user to trigger this hook (https://forum.yunohost.org/t/hook-when-a-user-is-added-in-a-group/25437)

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

pwd=$(dirname $0)
filename=$(basename $0)

# Set vars for following script

# The file name is <priority>-<app>
app=${filename#*-}

domain=$(ynh_app_setting_get --app=$app --key=domain)
path=$(ynh_app_setting_get --app=$app --key=path)
install_dir="$(ynh_app_setting_get --app=$app --key=install_dir)"
db_name="$(ynh_app_setting_get --app=$app --key=db_name)"
group_sync_enabled="$(ynh_app_setting_get --app=$app --key=group_sync_enabled)"
group_sync_included_organisations="$(ynh_app_setting_get --app=$app --key=group_sync_included_organisations)"
group_sync_excluded_organisations="$(ynh_app_setting_get --app=$app --key=group_sync_excluded_organisations)"
group_sync_included_ynh_group="$(ynh_app_setting_get --app=$app --key=group_sync_included_ynh_group)"
group_sync_excluded_ynh_group="$(ynh_app_setting_get --app=$app --key=group_sync_excluded_ynh_group)"

# Load common variables and helpers
source ${pwd}/../../apps/${app}/scripts/_common.sh

pushd ${pwd}/../../apps/${app}/scripts/
set_forgejo_login_source
popd
synchronize_users
