#!/bin/bash

YNH_HELPERS_VERSION=2.1

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

pwd=$(dirname $0)
filename=$(basename $0)

# Set vars for following script

# The file name is <priority>-<app>
app=${filename#*-}

domain=$(ynh_app_setting_get --app=$app --key=domain)
path=$(ynh_app_setting_get --app=$app --key=path)

# Load common variables and helpers
source ${pwd}/../../apps/${app}/scripts/_common.sh

set_forgejo_login_source
synchronize_users
