#!/bin/bash

source ./_common.sh
source /usr/share/yunohost/helpers

ynh_app_config_validate() {
    # Ensure to not show the registration button when the registration is disabled
    if [ "$disable_registration" == 'true' ]; then
        show_registration_button=false
    fi
    _ynh_app_config_validate
}

ynh_app_config_apply() {
    _ynh_app_config_apply
    migration_enabled="$(ynh_app_setting_get --app="$app" --key=migration_enabled)"
    if [[ "$migration_enabled" = "true" ]]; then
        ynh_app_setting_set --key=migration_allowed_domains--value='*'
    else
        ynh_app_setting_set --key=migration_allowed_domains --value=''
    fi
    ynh_config_add --template="app.ini" --destination="$install_dir/custom/conf/app.ini"
    set_forgejo_login_source
}

run__sync_groups_mapping() {
    set_forgejo_login_source
    synchronize_users
}

#=================================================
# SELECT THE ACTION FOLLOWING THE GIVEN ARGUMENT
#=================================================
ynh_app_config_run "$1"
