#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Load common variables and helpers
source ./_common.sh

# IMPORT GENERIC HELPERS
source /usr/share/yunohost/helpers

#=================================================
# Create install and data subdirs
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir" --source_id="runner"

xz -d "$install_dir/forgejo.xz"
chmod +x "$install_dir/forgejo"
chmod +x "$install_dir/forgejo-runner"

mkdir -p "$install_dir/custom/conf"

chmod -R o-rwx "$install_dir/custom"
chown -R $app:$app "$install_dir/custom"

#=================================================
# KEYS GENERATION
#=================================================

secret_key=$($install_dir/forgejo generate secret SECRET_KEY)
lfs_jwt_secret=$($install_dir/forgejo generate secret JWT_SECRET)
internal_token=$($install_dir/forgejo generate secret INTERNAL_TOKEN)
oauth2_jwt_secret=$($install_dir/forgejo generate secret JWT_SECRET)
ynh_app_setting_set --app=$app --key=secret_key --value=$secret_key
ynh_app_setting_set --app=$app --key=lfs_jwt_secret --value=$lfs_jwt_secret
ynh_app_setting_set --app=$app --key=internal_token --value=$internal_token
ynh_app_setting_set --app=$app --key=oauth2_jwt_secret --value=$oauth2_jwt_secret

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ssh_port=$(grep -P "Port\s+\d+" /etc/ssh/sshd_config | grep -P -o "\d+")
ynh_add_config --template="app.ini" --destination="$install_dir/custom/conf/app.ini"

chmod 640 "$install_dir/custom/conf/app.ini"
chown $app:$app "$install_dir/custom/conf/app.ini"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=1

ynh_add_systemd_config
ynh_add_systemd_config --service=${app}_runner --template="runner.service"

ynh_add_nginx_config

# Use logrotate to manage application logfile(s)
ynh_use_logrotate --logfile "/var/log/$app" --nonappend

chown -R $app:$app "/var/log/$app"
chmod u=rwX,g=rX,o= "/var/log/$app"

yunohost service add $app --description="Forgejo" --log="/var/log/$app/forgejo.log"
yunohost service add ${app}_runner --description="Forgejo runner" --log="/var/log/$app/forgejo.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

secret=$(openssl rand -hex 20)

pushd $install_dir
	ynh_exec_warn_less ynh_exec_as $app ./forgejo forgejo-cli actions register --name runner --scope $domain --secret "$secret"
	ynh_exec_warn_less ynh_exec_as $app ./forgejo-runner create-runner-file --instance https://$domain$path --secret "$secret"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/forgejo.log" --line_match="Starting new Web server: tcp:127.0.0.1:"
ynh_systemd_action --service_name=${app}_runner --action="start" --log_path="systemd"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression --message="Configuring Fail2Ban..." --weight=1

ynh_add_fail2ban_config --logpath "/var/log/$app/forgejo.log" --failregex ".*Failed authentication attempt for .* from <HOST>" --max_retry 5

#=================================================
# LDAP CONFIGURATION
#=================================================
ynh_script_progression --message="Adding LDAP configuration..." --weight=1

set_forgejo_login_source
enable_login_source_sync

# API user creation
create_forgejo_api_user

# YunoHost user creation
synchronize_users

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
