#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

xz -d "$install_dir/forgejo.xz"
chmod +x "$install_dir/forgejo"

mkdir -p "$install_dir/custom/conf"

chmod -R o-rwx "$install_dir/custom"
chown -R "$app:$app" "$install_dir/custom"

#=================================================
# KEYS GENERATION
#=================================================

secret_key=$("$install_dir/forgejo" generate secret SECRET_KEY)
lfs_jwt_secret=$("$install_dir/forgejo" generate secret JWT_SECRET)
internal_token=$("$install_dir/forgejo" generate secret INTERNAL_TOKEN)
oauth2_jwt_secret=$("$install_dir/forgejo" generate secret JWT_SECRET)
ynh_app_setting_set --key=secret_key --value="$secret_key"
ynh_app_setting_set --key=lfs_jwt_secret --value="$lfs_jwt_secret"
ynh_app_setting_set --key=internal_token --value="$internal_token"
ynh_app_setting_set --key=oauth2_jwt_secret --value="$oauth2_jwt_secret"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ssh_port=$(grep -P "Port\s+\d+" /etc/ssh/sshd_config | grep -P -o "\d+")
ynh_config_add --template="app.ini" --destination="$install_dir/custom/conf/app.ini"

chmod 640 "$install_dir/custom/conf/app.ini"
chown "$app:$app" "$install_dir/custom/conf/app.ini"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

ynh_config_add_nginx

ynh_config_add_logrotate  "/var/log/$app"

yunohost service add "$app" --description="Forgejo" --log="/var/log/$app/forgejo.log"

ynh_config_add_fail2ban --logpath "/var/log/$app/forgejo.log" --failregex ".*Failed authentication attempt for .* from <HOST>"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/forgejo.log" --wait_until="Starting new Web server: tcp:127.0.0.1:"

#=================================================
# LDAP CONFIGURATION
#=================================================
ynh_script_progression "Adding LDAP configuration..."

set_forgejo_login_source
enable_login_source_sync

# API user creation
create_forgejo_api_user

# Yunohost user creation
synchronize_users

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
