#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_script_progression "Removing systemd configuration..."
ynh_config_remove_systemd

# Remove the app-specific logrotate config
ynh_script_progression "Removing logrotate configuration..."
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_script_progression "Removing NGINX web server configuration..."
ynh_config_remove_nginx

# Remove the dedicated Fail2Ban config
ynh_script_progression "Removing Fail2Ban configuration..."
ynh_config_remove_fail2ban

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
